apiVersion: apps/v1
kind: Deployment
metadata:
  name: java
  labels:
    app: java
spec:
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
        - name: java
          image: hello-world-java
          ports:
            - containerPort: 8989
